steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'test-2-generation', 
           '--runtime', 'python39', 
           '--trigger-http', 
           '--allow-unauthenticated', 
           '--entry-point', 'hello_http', 
           '--region', 'europe-west9', 
           '--source', '.',
           '--gen2',
           '--timeout=30m']

