steps:
  # Étape pour installer les dépendances
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Étape pour copier le code source vers Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '.'
      - 'gs://gcf-v2-sources-633227318863-europe-west9/${_SUBSTITUTIONS_BRANCH}/'

  # Étape pour déployer la fonction Cloud à partir du code source téléchargé
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy function-1 \
          --runtime python312 \
          --trigger-http \
          --entry-point hello_http \
          --source gs://gcf-v2-sources-633227318863-europe-west9/${_SUBSTITUTIONS_BRANCH}/ \
          --region europe-west9

# Substitutions pour remplacer les espaces réservés
substitutions:
  _YOUR_BUCKET_NAME: 'gcf-v2-sources-633227318863-europe-west9'
  _SUBSTITUTIONS_BRANCH: 'main'  # Valeur par défaut pour le nom de la branche
