steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'TestLoubna', 
           '--runtime', 'python39', 
           '--trigger-http', 
           '--allow-unauthenticated', 
           '--entry-point', 'hello_http', 
           '--region', 'europe-west1', 
           '--source', '.']
timeout: '540s'
