steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'function-test1', '--runtime', 'python39', '--trigger-http', '--allow-unauthenticated', '--entry-point', 'hello_http']

timeout: '540s'
