
steps:
  # Step to install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']


  # Step to upload the source code to Google Cloud Storage
 - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '.'
      - 'gs://gcf-v2-sources-633227318863-europe-west9/${_BRANCH_NAME}/'

  # Étape pour déployer la fonction Cloud à partir du code source téléchargé
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy function-1 \
          --runtime python312 \
          --trigger-http \
          --entry-point hello_http \
          --source gs://gcf-v2-sources-633227318863-europe-west9/${_BRANCH_NAME}/ \
          --region europe-west9

# Substitutions pour remplacer les espaces réservés
substitutions:
  _YOUR_BUCKET_NAME: 'gcf-v2-sources-633227318863-europe-west9'

# Valeur par défaut pour le nom de la branche
_BRANCH_NAME: 'main'
